### ISSUE TITLE
Add black and flake8 as linter check

### ISSUE THREAD

**Issue by delijati** [KiraPC/fastapi-router-controller#17]
I use for all my projects https://github.com/psf/black and https://github.com/PyCQA/flake8. With this config `.flake8`.
This would prevent all this formatting changes ;)

Example for my pipeline https://gitlab.com/delijati/tchotcho/-/blob/master/.gitlab-ci.yml#L11
```
[flake8]
# https://github.com/psf/black#slices for E203
ignore = E501 W503 W504 E203
max-line-length = 88
max-complexity = 10
```

**Comment by KiraPC** [comment]
Introduced!
