### ISSUE TITLE
Setup.py has no version

### ISSUE THREAD

**Issue by delijati** [KiraPC/fastapi-router-controller#9]
In the `setup.py` the version needs to be set hard https://github.com/KiraPC/fastapi-router-controller/blob/31fa13b8031a21054509e7deee7f4f76a1d9d3a0/setup.py#L17 won't work. pip or setuptools are also checking locally the version,  but this obviously won't work as env variable `RELEASE_VERSION` is not set (and also should not be). A simple `sed` and writing the number is sufficient.

**Comment by KiraPC** [comment]
@delijati The idea is that the library is built by a Github action when a new tag is created. In that Action, I defined the env var RELEASE_VERSION.

**Comment by delijati** [comment]
Yes that works and the uploaded packge has the right version. But if you install it it will always have the version `0.0.0` -> as the variable `RELEASE_VERSION` locally is not set.

**Comment by delijati** [comment]
```
❯ env/bin/pip install fastapi_router_controller                                                                                                                                                                   :(
Processing /xxx/.cache/pip/wheels/70/b9/cc/4a9343271a85f22934c54751b127cf76deec60e45ecf44d5e2/fastapi_router_controller-0.0.0-py3-none-any.whl
Requirement already satisfied: fastapi==0.63.0 in ./env/lib/python3.8/site-packages (from fastapi_router_controller) (0.63.0)
Requirement already satisfied: starlette==0.13.6 in ./env/lib/python3.8/site-packages (from fastapi==0.63.0->fastapi_router_controller) (0.13.6)
Requirement already satisfied: pydantic<2.0.0,>=1.0.0 in ./env/lib/python3.8/site-packages (from fastapi==0.63.0->fastapi_router_controller) (1.8.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in ./env/lib/python3.8/site-packages (from pydantic<2.0.0,>=1.0.0->fastapi==0.63.0->fastapi_router_controller) (3.7.4.3)
Installing collected packages: fastapi-router-controller
Successfully installed fastapi-router-controller-0.0.0
```
-> **fastapi-router-controller-0.0.0**

**Comment by KiraPC** [comment]
@delijati Damn, yes, I understood. Do you have some idea to made it work both actions and locally?

**Comment by delijati** [comment]
See https://github.com/KiraPC/fastapi-router-controller/pull/11

**Comment by delijati** [comment]
awesome
